# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ansible_config_path',
            field=models.CharField(default=b'~', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='default_inventory',
            field=models.CharField(default=b'hosts', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='default_user',
            field=models.CharField(default=b'ubuntu', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='playbook_path',
            field=models.CharField(default=b'~', max_length=200),
        ),
    ]
