# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0003_auto_20170510_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ansible.Project')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
