# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0004_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(default=b'~/', max_length=200)),
                ('ansible_config', models.CharField(default=b'~/', max_length=200)),
                ('inventory', models.CharField(default=b'hosts', max_length=200)),
                ('user', models.CharField(default=b'ubuntu', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'playbooks',
            },
        ),
        migrations.RemoveField(
            model_name='registry',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
