# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0005_auto_20170515_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item', models.FilePathField(match=b'*.yml', path=b'/opt/playbooks/', recursive=True)),
            ],
            options={
                'verbose_name_plural': 'registries',
            },
        ),
    ]
