# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0006_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='ansible_config',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='path',
        ),
        migrations.AddField(
            model_name='registry',
            name='playbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ansible.Playbook'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='item',
            field=models.FilePathField(path=b'/opt/app/playbooks/', recursive=True),
        ),
    ]
