# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0008_playbook_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='item',
            new_name='file_path',
        ),
    ]
