# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0011_delete_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=39)),
            ],
            options={
                'verbose_name': 'github project',
                'verbose_name_plural': 'github projects',
            },
        ),
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('repository_owner', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'gitlab project',
                'verbose_name_plural': 'gitlab projects',
            },
        ),
    ]
