# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0013_auto_20170618_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbook',
            options={'verbose_name': 'playbook', 'verbose_name_plural': 'playbooks'},
        ),
    ]
