# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170524_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('repository_owner', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'gitlab project',
                'verbose_name_plural': 'gitlab projects',
            },
        ),
    ]
